language: ruby
rvm:
  - 2.6.5

services:
  - postgresql

env:
  - POSTGRES_USER=travis POSTGRES_PASSWORD=password POSTGRES_HOST=localhost POSTGRES_DEVELOPMENT_DB=acebook_development POSTGRES_TEST_DB=acebook_test POSTGRES_DB=acebook

before_script:
  — rake db:create
  — rake db:migrate

script:
  — rspec

